### ISSUE TITLE
What is MNN version do u use in this repo

### ISSUE THREAD

**Issue by kikirizki** [cmdbug/MNN_Demo#1]
HI thanks for your great works, but I'm wondering what is MNN version do u use in this repo, I tried to load model converted using MNN 1.2.0 this repo keep crashing, thank you

**Comment by cmdbug** [comment]
Version 1.0 is normal, other versions may need to re-convert the model. Different versions of the conversion tool seem to have problems.

**Comment by kikirizki** [comment]
Thank you so much Now it is work
